name: CI

on:
    push:
        branches: [main, master]
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - run: bun install --frozen-lockfile
            - run: bun run web:fmt.chk && bun run web:chk
            - run: bun run service:fmt.chk && bun run service:chk
